-- Create tables for the forum

-- Threads table
CREATE TABLE public.threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    post_count INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Posts table
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL REFERENCES public.threads(id) ON DELETE CASCADE,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indexes for better performance
CREATE INDEX idx_posts_thread_id ON public.posts(thread_id);
CREATE INDEX idx_threads_created_at ON public.threads(created_at DESC);
CREATE INDEX idx_posts_created_at ON public.posts(created_at);

-- Create a function to increment post count in threads
CREATE OR REPLACE FUNCTION public.increment_post_count(thread_id_param BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.threads
  SET post_count = post_count + 1,
      updated_at = timezone('utc'::text, now())
  WHERE id = thread_id_param;
END;
$$;

-- Set up Row Level Security (RLS)
-- Enable RLS on tables
ALTER TABLE public.threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Create policies for anonymous access (read-only)
CREATE POLICY "Allow anonymous read access" ON public.threads
    FOR SELECT USING (true);

CREATE POLICY "Allow anonymous read access" ON public.posts
    FOR SELECT USING (true);

-- Create policies for anonymous insert (to allow posting without authentication)
CREATE POLICY "Allow anonymous insert" ON public.threads
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous insert" ON public.posts
    FOR INSERT WITH CHECK (true);

-- Insert some sample data
INSERT INTO public.threads (title, author, post_count)
VALUES 
    ('Welcome to THE UNDERWEB Forum', 'Admin', 3),
    ('Retro Web Design Tips', 'WebDesigner98', 2),
    ('Share Your Favorite Web 1.0 Sites', 'RetroFan', 2),
    ('Windows 98 Aesthetic Appreciation', 'VaporwaveEnthusiast', 2);

-- Insert sample posts
INSERT INTO public.posts (thread_id, author, content)
VALUES
    (1, 'Admin', 'Welcome to THE UNDERWEB forum! This is a place to discuss all things related to the retro web, Web 1.0 aesthetics, and the hidden corners of the internet.\n\nPlease keep discussions civil and on-topic.'),
    (1, 'RetroFan', 'Thanks for creating this forum! I''m excited to connect with other people who appreciate the old-school web aesthetic.'),
    (1, 'WebDesigner98', 'This is awesome! I love the Windows 98 theme you''ve got going here.'),
    
    (2, 'WebDesigner98', 'Here are some tips for creating authentic Web 1.0 style websites:\n\n1. Use tables for layout\n2. Add plenty of animated GIFs\n3. Don''t forget the visitor counter\n4. Include a guestbook\n5. Use bright, contrasting colors\n\nWhat other tips would you add?'),
    (2, 'RetroFan', 'Don''t forget the "Under Construction" GIFs and the "Best viewed in Netscape Navigator" badges!'),
    
    (3, 'RetroFan', 'What are your favorite Web 1.0 era websites that are still online? I love browsing through these time capsules.\n\nMy favorites are:\n- Space Jam (1996): https://www.spacejam.com/1996/\n- The Dole/Kemp campaign site: https://www.dolekemp96.org/\n\nShare yours!'),
    (3, 'VaporwaveEnthusiast', 'I love the Heaven''s Gate website which is still up and unchanged since 1997: https://www.heavensgate.com/'),
    
    (4, 'VaporwaveEnthusiast', 'There''s something so nostalgic about the Windows 98 UI. The beveled buttons, the iconic start menu, the satisfying click sounds...\n\nWhat are your favorite elements of the Windows 98 aesthetic?'),
    (4, 'WebDesigner98', 'I love the error messages with their little icons! And the card games with those green backgrounds. So much character compared to modern flat design.');
