-- Enhanced forum setup with user authentication, profiles, categories, and moderation
-- This file contains only the additional changes needed for the enhanced features

-- Create extension for UUID generation if not exists
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Users table (replacing the simple author field in threads and posts)
CREATE TABLE public.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    avatar_url TEXT,
    bio TEXT,
    is_admin BOOLEAN DEFAULT false,
    is_moderator BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Categories table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    slug TEXT UNIQUE NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Moderation actions table
CREATE TABLE public.moderation_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moderator_id UUID NOT NULL REFERENCES public.users(id),
    action_type TEXT NOT NULL, -- 'delete_post', 'lock_thread', 'ban_user', etc.
    target_type TEXT NOT NULL, -- 'post', 'thread', 'user', etc.
    target_id TEXT NOT NULL, -- ID of the target (post ID, thread ID, user ID, etc.)
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- User sessions table
CREATE TABLE public.user_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Alter existing tables to add new columns

-- Alter threads table to add user_id, category_id, and moderation fields
ALTER TABLE public.threads 
    ADD COLUMN user_id UUID REFERENCES public.users(id),
    ADD COLUMN category_id BIGINT REFERENCES public.categories(id),
    ADD COLUMN is_pinned BOOLEAN DEFAULT false,
    ADD COLUMN is_locked BOOLEAN DEFAULT false;

-- Alter posts table to add user_id and editing fields
ALTER TABLE public.posts 
    ADD COLUMN user_id UUID REFERENCES public.users(id),
    ADD COLUMN is_edited BOOLEAN DEFAULT false,
    ADD COLUMN edited_at TIMESTAMP WITH TIME ZONE;

-- Create additional indexes for better performance
CREATE INDEX idx_threads_category_id ON public.threads(category_id);
CREATE INDEX idx_threads_user_id ON public.threads(user_id);
CREATE INDEX idx_posts_user_id ON public.posts(user_id);
CREATE INDEX idx_user_sessions_token ON public.user_sessions(token);
CREATE INDEX idx_user_sessions_expires_at ON public.user_sessions(expires_at);

-- Create additional functions

-- Function to check if user is admin
CREATE OR REPLACE FUNCTION public.is_admin(user_id_param UUID)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  is_admin_result BOOLEAN;
BEGIN
  SELECT is_admin INTO is_admin_result
  FROM public.users
  WHERE id = user_id_param;
  
  RETURN COALESCE(is_admin_result, false);
END;
$$;

-- Function to check if user is moderator
CREATE OR REPLACE FUNCTION public.is_moderator(user_id_param UUID)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  is_moderator_result BOOLEAN;
BEGIN
  SELECT (is_moderator OR is_admin) INTO is_moderator_result
  FROM public.users
  WHERE id = user_id_param;
  
  RETURN COALESCE(is_moderator_result, false);
END;
$$;

-- Function to authenticate user
CREATE OR REPLACE FUNCTION public.authenticate_user(email_param TEXT, password_param TEXT)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  user_id UUID;
BEGIN
  -- In a real implementation, you would hash the password and compare with the stored hash
  -- For this example, we're just comparing the raw password (not secure!)
  SELECT id INTO user_id
  FROM public.users
  WHERE email = email_param AND password_hash = password_param;
  
  RETURN user_id;
END;
$$;

-- Function to create a session
CREATE OR REPLACE FUNCTION public.create_session(user_id_param UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  token TEXT;
  session_id UUID;
BEGIN
  -- Generate a random token
  token := encode(gen_random_bytes(32), 'hex');
  
  -- Create a new session
  INSERT INTO public.user_sessions (user_id, token, expires_at)
  VALUES (user_id_param, token, timezone('utc'::text, now()) + interval '7 days')
  RETURNING id INTO session_id;
  
  RETURN token;
END;
$$;

-- Set up Row Level Security (RLS) for new tables
-- Enable RLS on tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.moderation_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;

-- Create policies for users table
CREATE POLICY "Allow public read access to users" ON public.users
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" ON public.users
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow admins to update any user" ON public.users
    FOR UPDATE USING (public.is_admin(auth.uid()));

-- Create policies for categories table
CREATE POLICY "Allow public read access to categories" ON public.categories
    FOR SELECT USING (true);

CREATE POLICY "Allow admins to manage categories" ON public.categories
    FOR ALL USING (public.is_admin(auth.uid()));

-- Create policies for moderation_actions table
CREATE POLICY "Allow moderators to create moderation actions" ON public.moderation_actions
    FOR INSERT WITH CHECK (public.is_moderator(auth.uid()));

CREATE POLICY "Allow moderators to view moderation actions" ON public.moderation_actions
    FOR SELECT USING (public.is_moderator(auth.uid()));

-- Create policies for user_sessions table
CREATE POLICY "Allow users to view their own sessions" ON public.user_sessions
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own sessions" ON public.user_sessions
    FOR DELETE USING (auth.uid() = user_id);

-- Update existing policies for threads and posts tables
DROP POLICY IF EXISTS "Allow anonymous insert" ON public.threads;
DROP POLICY IF EXISTS "Allow anonymous insert" ON public.posts;

CREATE POLICY "Allow authenticated users to create threads" ON public.threads
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Allow thread owners to update their threads" ON public.threads
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Allow moderators to update any thread" ON public.threads
    FOR UPDATE USING (public.is_moderator(auth.uid()));

CREATE POLICY "Allow thread owners to delete their threads" ON public.threads
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Allow moderators to delete any thread" ON public.threads
    FOR DELETE USING (public.is_moderator(auth.uid()));

CREATE POLICY "Allow authenticated users to create posts" ON public.posts
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Allow post owners to update their posts" ON public.posts
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Allow moderators to update any post" ON public.posts
    FOR UPDATE USING (public.is_moderator(auth.uid()));

CREATE POLICY "Allow post owners to delete their posts" ON public.posts
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Allow moderators to delete any post" ON public.posts
    FOR DELETE USING (public.is_moderator(auth.uid()));

-- Insert sample data

-- Insert sample categories
INSERT INTO public.categories (name, description, slug, display_order)
VALUES 
    ('General Discussion', 'General topics related to THE UNDERWEB', 'general', 1),
    ('Retro Web Design', 'Discussions about Web 1.0 and retro web design', 'retro-web-design', 2),
    ('Windows 98 Aesthetic', 'All things related to the Windows 98 look and feel', 'windows-98', 3),
    ('Web Rings & Link Directories', 'Discover and share web rings and link directories', 'web-rings', 4),
    ('Help & Support', 'Get help with THE UNDERWEB and related topics', 'help-support', 5);

-- Insert sample users
INSERT INTO public.users (username, email, password_hash, display_name, is_admin, is_moderator)
VALUES 
    ('admin', 'admin@underweb.example.com', 'admin_password_hash', 'Admin', true, true),
    ('moderator', 'mod@underweb.example.com', 'mod_password_hash', 'Moderator', false, true),
    ('webdesigner98', 'webdesigner@example.com', 'user_password_hash', 'WebDesigner98', false, false),
    ('retrofan', 'retrofan@example.com', 'user_password_hash', 'RetroFan', false, false),
    ('vaporwaveenthusiast', 'vaporwave@example.com', 'user_password_hash', 'VaporwaveEnthusiast', false, false);

-- Create a trigger to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON categories FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Update existing triggers
CREATE TRIGGER update_threads_updated_at BEFORE UPDATE ON threads FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON posts FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Migration script to update existing data
-- This will associate existing threads and posts with the new users based on the author field
DO $$
DECLARE
    thread_record RECORD;
    post_record RECORD;
    user_id UUID;
    category_id BIGINT;
BEGIN
    -- For each thread, find or create a user with the author name and update the user_id
    FOR thread_record IN SELECT id, author FROM public.threads LOOP
        -- Try to find a user with the matching username
        SELECT id INTO user_id FROM public.users WHERE username = thread_record.author;
        
        -- If no user found, create one
        IF user_id IS NULL THEN
            INSERT INTO public.users (username, email, password_hash, display_name)
            VALUES (thread_record.author, lower(thread_record.author) || '@example.com', 'migrated_password', thread_record.author)
            RETURNING id INTO user_id;
        END IF;
        
        -- Assign a default category (General Discussion)
        SELECT id INTO category_id FROM public.categories WHERE slug = 'general';
        
        -- Update the thread with the user_id and category_id
        UPDATE public.threads
        SET user_id = user_id,
            category_id = category_id
        WHERE id = thread_record.id;
    END LOOP;
    
    -- For each post, find or create a user with the author name and update the user_id
    FOR post_record IN SELECT id, author FROM public.posts LOOP
        -- Try to find a user with the matching username
        SELECT id INTO user_id FROM public.users WHERE username = post_record.author;
        
        -- If no user found, create one
        IF user_id IS NULL THEN
            INSERT INTO public.users (username, email, password_hash, display_name)
            VALUES (post_record.author, lower(post_record.author) || '@example.com', 'migrated_password', post_record.author)
            RETURNING id INTO user_id;
        END IF;
        
        -- Update the post with the user_id
        UPDATE public.posts
        SET user_id = user_id
        WHERE id = post_record.id;
    END LOOP;
END;
$$;

-- Insert sample moderation actions
DO $$
DECLARE
    admin_id UUID;
    mod_id UUID;
    thread_id BIGINT;
BEGIN
    -- Get user IDs
    SELECT id INTO admin_id FROM public.users WHERE username = 'admin';
    SELECT id INTO mod_id FROM public.users WHERE username = 'moderator';
    
    -- Get a thread ID
    SELECT id INTO thread_id FROM public.threads LIMIT 1;
    
    -- Insert sample moderation actions
    INSERT INTO public.moderation_actions (moderator_id, action_type, target_type, target_id, reason)
    VALUES
        (admin_id, 'pin_thread', 'thread', thread_id::text, 'Welcome thread should be pinned'),
        (mod_id, 'edit_post', 'post', '1', 'Fixed formatting issues');
END;
$$;
